# Generated by Django 4.2.5 on 2023-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_movment_reciver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
