# Generated by Django 4.2.5 on 2023-09-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productdetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='inventory.side'),
        ),
    ]
